window.MeetFitMockData = {
  directoryPeople: [
    {
      id: "minji",
      name: "정소희",
      title: "프로덕트 디자이너",
      team: "Product Design",
      email: "sohee.jung@company.com",
      initial: "정",
      summary: "가능한 시간이에요",
    },
    {
      id: "junho",
      name: "박준호",
      title: "머신러닝 팀장",
      team: "Engineering",
      email: "junho.park@company.com",
      initial: "박",
      summary: "외근 없음, 오전이 좋아요",
    },
    {
      id: "seoyeon",
      name: "이서연",
      title: "콘텐츠 매니저",
      team: "Content Strategy",
      email: "seoyeon.lee@company.com",
      initial: "이",
      summary: "점심 직후가 아니에요",
    },
    {
      id: "taeho",
      name: "최태오",
      title: "데이터 분석가",
      team: "Data",
      email: "taeho.choi@company.com",
      initial: "최",
      summary: "가능한 시간이에요",
    },
    {
      id: "yujin",
      name: "정유진",
      title: "디자인 팀장",
      team: "Design",
      email: "yujin.jung@company.com",
      initial: "정",
      summary: "함께 하면 가능해요",
    },
    {
      id: "harin",
      name: "오하린",
      title: "브랜드 매니저",
      team: "Brand",
      email: "harin.oh@company.com",
      initial: "오",
      summary: "함께 참석 가능해요",
    },
    {
      id: "jiwon",
      name: "강지원",
      title: "플랫폼 엔지니어",
      team: "Platform",
      email: "jiwon.kang@company.com",
      initial: "강",
      summary: "오후 시간이 좋아요",
    },
    {
      id: "eunchae",
      name: "한은채",
      title: "CS 운영 매니저",
      team: "Customer Ops",
      email: "eunchae.han@company.com",
      initial: "한",
      summary: "수요일 외근이 있어요",
    },
    {
      id: "doyoon",
      name: "윤도윤",
      title: "백엔드 엔지니어",
      team: "Engineering",
      email: "doyoon.yoon@company.com",
      initial: "윤",
      summary: "배포 시간만 피하면 돼요",
    },
    {
      id: "sumin",
      name: "차수민",
      title: "리서처",
      team: "UX Research",
      email: "sumin.cha@company.com",
      initial: "차",
      summary: "응답 대기 중이에요",
    },
  ],

  defaultAttendeeRoles: [
    { id: "minji", required: true },
    { id: "junho", required: true },
    { id: "seoyeon", required: true },
    { id: "taeho", required: true },
    { id: "harin", required: false },
    { id: "jiwon", required: false },
  ],

  defaultTimeCriteria: {
    workStart: "09:00",
    workEnd: "18:00",
    lunchStart: "12:00",
    lunchEnd: "13:00",
  },

  weeklyCandidateDays: [
    { dateKey: "7.13", label: "7.13", weekday: "월" },
    { dateKey: "7.14", label: "7.14", weekday: "화" },
    { dateKey: "7.15", label: "7.15", weekday: "수" },
    { dateKey: "7.16", label: "7.16", weekday: "목" },
    { dateKey: "7.17", label: "7.17", weekday: "금" },
  ],

  candidateRows: [
    {
      id: "jul14-1000",
      dateKey: "7.14",
      day: "7. 14 (화)",
      weekday: "화",
      start: "10:00",
      end: "11:00",
      time: "10:00 - 11:00",
      priority: "recommended",
      score: 95,
      beforeBuffer: "앞 1시간 비어 있음",
      afterBuffer: "뒤 30분 비어 있음",
      nearby: "11:30 주간 싱크",
      availability: {
        requiredAvailable: 4,
        requiredTotal: 4,
        optionalAvailable: 2,
        optionalTotal: 2,
        issues: [],
      },
    },
    {
      id: "jul15-1000",
      dateKey: "7.15",
      day: "7. 15 (수)",
      weekday: "수",
      start: "10:00",
      end: "11:00",
      time: "10:00 - 11:00",
      priority: "review",
      score: 85,
      beforeBuffer: "앞 30분 비어 있음",
      afterBuffer: "뒤 1시간 비어 있음",
      nearby: "09:30 외부 미팅",
      availability: {
        requiredAvailable: 4,
        requiredTotal: 4,
        optionalAvailable: 2,
        optionalTotal: 2,
        issues: [
          { name: "박준호", role: "required", type: "nearby", text: "09:30-10:00 외부 미팅 직후라 이동 여유가 짧아요" },
        ],
      },
    },
    {
      id: "jul14-1300",
      dateKey: "7.14",
      day: "7. 14 (화)",
      weekday: "화",
      start: "13:00",
      end: "14:00",
      time: "13:00 - 14:00",
      priority: "review",
      score: 75,
      beforeBuffer: "앞 점심시간",
      afterBuffer: "뒤 1시간 비어 있음",
      nearby: "12:00 점심시간",
      availability: {
        requiredAvailable: 4,
        requiredTotal: 4,
        optionalAvailable: 1,
        optionalTotal: 2,
        issues: [
          { name: "오하린", role: "optional", type: "busy", text: "13:00-14:00 브랜드 리뷰가 있어 참석이 어려워요" },
        ],
      },
    },
  ],

  meetingDetails: {
    name: "상품 운영 회고",
    duration: "1시간",
    range: "2026. 7. 13 (월) - 7. 17 (금)",
  },

  replyDeadline: "내일 18:00",

  responseOptions: [
    { id: "ok", status: "ok", mark: "✓", text: "괜찮아요" },
    { id: "any", status: "any", mark: "·", text: "상관없어요" },
    { id: "warn", status: "warn", mark: "!", text: "가능하지만 조금 부담돼요" },
    { id: "no", status: "no", mark: "×", text: "어려워요" },
  ],

  defaultResponseSelections: {
    "jul14-1000": "ok",
    "jul15-1000": "warn",
    "jul14-1300": "warn",
  },

  defaultResponseContextChecks: {
    lunch: true,
    travel: true,
    morning: false,
    afternoon: false,
    other: false,
  },

  recommendations: [
    {
      id: "final-jul14-1000",
      candidateId: "jul14-1000",
      badge: "최적 후보",
      date: "7. 14 (화)",
      time: "10:00 - 11:00",
      reason: "필수 참석자가 모두 가능하고, 선택 참석자도 함께할 수 있어요. 점심 직후나 외근 이동 부담도 없어요.",
      matchLevel: "높음",
      matchTone: "high",
      tone: "green",
    },
    {
      id: "final-jul15-1000",
      candidateId: "jul15-1000",
      badge: "대안으로 가능해요",
      date: "7. 15 (수)",
      time: "10:00 - 11:00",
      reason: "필수 참석자는 모두 가능해요. 다만 박준호님은 직전 외부 미팅이 있어 이동 여유가 짧아요.",
      matchLevel: "보통",
      matchTone: "mid",
      tone: "green",
    },
    {
      id: "final-jul14-1300",
      candidateId: "jul14-1300",
      badge: "가능하지만 부담이 있어요",
      date: "7. 14 (화)",
      time: "13:00 - 14:00",
      reason: "필수 참석자는 가능하지만 점심 직후 부담이 있고, 선택 참석자 한 명은 기존 일정이 있어요.",
      matchLevel: "낮음",
      matchTone: "low",
      tone: "red",
    },
  ],

  recommendationVotes: {
    "jul14-1000": [
      { personId: "junho", response: "ok", note: "앞뒤 일정 모두 괜찮아요" },
      { personId: "seoyeon", response: "ok", note: "회의 전후 부담 없어요" },
      { personId: "taeho", response: "ok", note: "괜찮아요" },
      { personId: "harin", response: "ok", note: "참석 가능해요" },
      { personId: "jiwon", response: "any", note: "상관없어요" },
    ],
    "jul15-1000": [
      { personId: "junho", response: "warn", note: "09:30-10:00 외부 미팅 직후라 이동 여유가 짧아요" },
      { personId: "seoyeon", response: "ok", note: "괜찮아요" },
      { personId: "taeho", response: "ok", note: "가능해요" },
      { personId: "harin", response: "any", note: "상관없어요" },
      { personId: "jiwon", response: "ok", note: "참석 가능해요" },
    ],
    "jul14-1300": [
      { personId: "junho", response: "ok", note: "가능해요" },
      { personId: "seoyeon", response: "warn", note: "점심 직후라 조금 부담돼요" },
      { personId: "taeho", response: "ok", note: "가능해요" },
      { personId: "harin", response: "no", note: "13:00-14:00 브랜드 리뷰가 있어 참석이 어려워요" },
      { personId: "jiwon", response: "any", note: "상관없어요" },
    ],
  },
};
